name: Deploy to Contabo VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/projects/opencart-farhan
            git pull origin main
            # Set permissions correctly after pull
            chmod -R 777 upload/system/storage upload/image
            docker-compose up -d --build --force-recreate --remove-orphans
